version: "3"
services:
  # creation: docker build -t rq170/covid:1.0.3 .
  covid:
    # replace username/repo:tag with your name and image details
    image: rq170/covid:1.0.2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.2"
          memory: 350M

      restart_policy:
        condition: on-failure

    ports:
      - "8081:80"

    networks:
      - webnet

networks:
  webnet:

