version: "3"
services:
  # creation: docker build -t rq170/covid:2.0.0 .
  # docker stack deploy -c docker-compose.yml mswarm1
  covid:
    # replace username/repo:tag with your name and image details
    image: rq170/covid:2.0.2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.3"
          memory: 350M

      restart_policy:
        condition: on-failure

    ports:
      - "8081:80"

    networks:
      - webnet

networks:
  webnet:

