version: "3"
services:
  # docker build -t rq170/covid:2.0.6 .
  # docker push rq170/covid:2.0.6
  # docker stack deploy -c docker-compose.yml mswarm1
  covid:
    # replace username/repo:tag with your name and image details
    image: rq170/covid:2.2.1
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.5"
          memory: 100M

      restart_policy:
        condition: on-failure

    ports:
      - "8081:80"

    networks:
      - webnet

networks:
  webnet:

